# Generated by Django 5.1 on 2024-09-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_username', models.CharField(blank=True, max_length=150, null=True)),
                ('chat_id', models.BigIntegerField()),
                ('serial_number', models.CharField(max_length=100)),
                ('video_link', models.URLField()),
            ],
        ),
    ]
