# Generated by Django 5.1 on 2024-09-25 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='video_link',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='chat_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='VideoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_links', to='botapp.userdata')),
            ],
            options={
                'unique_together': {('user', 'video_link')},
            },
        ),
    ]
