# Generated by Django 5.1 on 2024-09-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('botapp', '0002_remove_userdata_video_link_alter_userdata_chat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videolink',
            name='video_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
